name: build-release-with-vulkan-windows

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4
        
      - name: Setup
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: UCRT64
          install: >-
            base-devel
            git
            zip
            mingw-w64-ucrt-x86_64-toolchain
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-SDL2
            mingw-w64-ucrt-x86_64-openblas
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-vulkan-devel
            mingw-w64-ucrt-x86_64-shaderc
            
      - name: Build using CMake
        shell: msys2 {0}
        run: |
            cmake -B build -DWHISPER_SDL2=ON -DBUILD_SHARED_LIBS=ON -DGGML_VULKAN=ON -DGGML_BLAS=ON -DGGML_BLAS_VENDOR=OpenBLAS
            cmake --build build --config Release -j
            cp ../../../../ucrt64/bin/libgcc_s_seh-1.dll build/bin/
            cp ../../../../ucrt64/bin/libopenblas.dll build/bin/
            cp ../../../../ucrt64/bin/libwinpthread* build/bin/
            cp ../../../../ucrt64/bin/libgfortran* build/bin/
            cp ../../../../ucrt64/bin/libgomp* build/bin/
            cp ../../../../ucrt64/bin/libquadmath* build/bin/
            cp ../../../../ucrt64/bin/libstdc++* build/bin/
            cp ../../../../ucrt64/bin/SDL2.dll build/bin/
            cp examples/server/*.bat build/bin/
            
            zip -r release-windows.zip build/bin/ examples/server/public/
            sha256sum release-windows.zip
            
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: Release ${{ github.run_id }}\n<code>whisper-server.exe -m ggml-large-v3-turbo.bin --host 0.0.0.0 --port 18181 -t 8 -l auto  --vad --vad-model ggml-silero-v6.2.0.bin -p 8 -mc 0 -di -pp -pr</code>
          tag_name: ${{ github.run_id }}
          name: build-windows-${{ github.run_id }}
          files: |
            release-windows.zip
